# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'colorreco_ui' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for colorreco_ui
  pod 'iOS-Color-Picker'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift'
  pod 'Alamofire'
#  pod 'ImagePicker'
 
 # platform :ios, '9.0'
 # pod 'ColorSlider', '~> 4.4'

end
